### ISSUE TITLE
Items overlap 

### ISSUE THREAD

**Issue by chucktobbes** [ferrouslights/Unity-Tetris-Grid-Inventory-System#2]
Hi Ben, 

nice little inventory system. While testing, I noticed two issues. The sort order of the items doesn't get updated, while placing this results in overlapping. And sometimes I get an IndexOutOfRangeException: while placing at the edge. 

Also, some features I will additionally add for my usage, in case you are curious:

- Slerp interpolation while rotating
- Option to hold and drag instead of click and release
- color notification when item isn't placeable

**Comment by ferrouslights** [comment]
Thanks for checking it out! I plan to eventually expand this and please feel free to PR any changes you have made that enrich the project.

**Comment by chucktobbes** [comment]
I am really struggling to move the pivot of the item from the top left corner to the middle, is there an easy workaround?

**Comment by ferrouslights** [comment]
The pivot helps keep each item in the bottom right from the mouse. When the controller rotates the item, it changes the pivot as well. Might be worth it to nest the image in a child object with .5, .5 pivots for Slerp rotations and keeping the root object 0,1. Then all that needs to be done is changing the rotation logic to Slerp and removing the pivot updates that the controller does.

**Comment by ferrouslights** [comment]
After this PR, I'm going to close this issue but I documented the other requests in separate issues for continued tracking.
